name: signal_messenger_toolkit
description: signal_messenger_toolkit is an unofficial Flutter toolkit for integrating with the Signal platform—built by the community and not officially endorsed by Signal
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ^3.24.0

dependencies:
  archive: ^4.0.7
  flutter:
    sdk: flutter
  flutter_image_compress: ^2.4.0
  image_cropper: ^9.1.0
  yaml: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  very_good_analysis: ^6.0.0
